### PR TITLE
Superconducting single qubit gates

### PR DESCRIPTION
**Pull request by ViktorPerunicic**
... fixed units but left values as is (if anyone has better superconducting qutrit values, pls let me know)

### CODE REVIEW

**Comment by charmasaur** [comment]
Looks fine to me, but I don't know anything about superconducting qutrits.

Could you replace "organise" with "organize" (when putting all the controls into a dict) and "reorganise" with "reorganize" (when exporting to CSV)?

**Comment by charmasaur** [comment]
FYI in my notebooks I also tweaked the intro slightly, to move the description of the system into the second sentence (see https://github.com/qctrl/notebooks/blame/717845322eb7f814465a576428ff38195be7f7ca/qctrl/Optimization_of_an_iSWAP_gate_with_leakage_suppression.ipynb#L9). If we want maximum consistency we should either make the same change here, or undo my change.

**Comment by ViktorPerunicic** [comment]
agree, I don't mind, either way,  @andrerrcarvalho any preference

**Comment by andrerrcarvalho** [comment]
I changed the other one as well to match @charmasaur 's flow. Let's stick to that.

**Comment by ViktorPerunicic** [comment]
Yea duration is bound by the Rabi rate, which raises an interesting question: Black Opal uses omage_max = 50MHz as an example for superconducting qubits, while in the IBM NB we use several GHz

**Comment by ViktorPerunicic** [comment]
@andrerrcarvalho I spotted you were busy, so I made changes to this also...

**Pull request merged**
