### PR TITLE
Dynamical decoupling notebook

### PR DESCRIPTION
**Pull request by andrerrcarvalho**
BOULDER OPAL notebook with dynamical decoupling sequences and filter functions

### CODE REVIEW

**Comment by andrerrcarvalho** [comment]
@ViktorPerunicic, there is a problem implementing the flow from the other notebook in this one. Here, the different sequences require different keyword arguments. I think I'll need to keep their creation in a separate cell. I'll implement the other changes.

**Comment by ViktorPerunicic** [comment]
@andrerrcarvalho sounds reasonable

**Comment by ViktorPerunicic** [comment]
btw I spotted the term "additive" noise in the text, I used "dephasing" noise as it has been used in titles of the existing NBs on the web. Do we want to make this uniform? @andrerrcarvalho @michaelhush

**Comment by andrerrcarvalho** [comment]
@ViktorPerunicic , we also have the term `additive` in the other notebook when referring to the way that noise is constructed in the package. Both notebooks use `dephasing` in the first markup cell.

**Comment by ViktorPerunicic** [comment]
you are right, sorry for confusing comment - for some reason I thought we ent the other way

**Comment by michaelhush** [comment]
@andrerrcarvalho The filter functions, in the ideal case with perfect pi pulses, should all have a downward slant. Some of the filter functions look "bad". This might be because of (a) and implementation bug in open controls, (I think this is unlikely as we checked them all with internal filter functions. (b) a due to the finite impulse size of the pi pulses.

To investigate (b) could you see if the get better with a higher Rabi rate? This is using the numerical filter function integrator, so there might also be a need to increase the number of samples to improve their quality.

**Pull request closed without merging**
