### PR TITLE
3 optimisation NBs (Black 569)

### PR DESCRIPTION
**Pull request by ViktorPerunicic**
Updated the 3 optimisation notebooks and also made filtered RC work properly with KevN as it required new segment types. 

@michaelhush have a look  - let me know if you want to iterate now, or I split them into 6, then we iterate one of them until UX looks good... updated others based on the same template.

### CODE REVIEW

**Comment by ViktorPerunicic** [comment]
@michaelhush just realised that I put you on the list earlier today but this did not generate review request!

**Comment by michaelhush** [comment]
LGTM. I'll approve. But technically we shouldn't merge this into master until updates to the python package are made live. I'll add @stevegore  as a reviewer and get his opinion on how to best manage that.

**Comment by stevegore** [comment]
And here I was thinking you wanted my advise on optimisations...

**Comment by ViktorPerunicic** [comment]
Ok - in the meantime I can tag on the split of examples in the NP on this PR? (https://q-ctrl.atlassian.net/browse/BLACK-934)

**Comment by michaelhush** [comment]
@ViktorPerunicic I think we will handle this manually. So plan is.

I'll close this PR but it will be sitting here ready to be released when release everything else.

Then make a new branch called BLACK-934 based on this one.

**Pull request closed without merging**
