### PR TITLE
Update qctrl notebooks to use Q-CTRL Python Visualizer

### PR DESCRIPTION
**Pull request by charmasaur**

### CODE REVIEW

**Comment by michaelhush** [comment]
@charmasaur @stevegore why is this failing circle CI?

**Comment by charmasaur** [comment]
This is the error:
```
#!/bin/sh -eo pipefail
# No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
Exited with code 1
```

Looks like you just merged the CL to add the config, I'll merge and we can see what happens when it re-runs (although I'm sure it will fail, because the notebooks don't run as-is -- they're missing API tokens, for instance).

**Comment by charmasaur** [comment]
Tests are now legit failing (visualizer package is missing), but as I mentioned before, even if we add the visualizer the tests won't pass until we can provide a dummy API key or something.

**Comment by stevegore** [comment]
Want me to merge the PR?

**Comment by michaelhush** [comment]
@stevegore should we turn off running the notebooks until we can figure out a solution for running the notebooks?

**Comment by stevegore** [comment]
Yeah makes sense.

**Comment by stevegore** [comment]
Status checks have been turned off for all notebooks.

**Pull request merged**
