### PR TITLE
 Calculation of noise filtering properties in driven controls

### PR DESCRIPTION
**Pull request by ViktorPerunicic**
The title changed from "Filter functions of pulses that are robust to dephasing" to "Calculation of noise filtering properties in driven controls".  Also added are the links into the intro.

### CODE REVIEW

**Comment by michaelhush** [comment]
Can you change the file name as well. Otherwise this looks good

**Comment by michaelhush** [comment]
Make sure you have an American spell checker on. Characterization, not characterization.

**Comment by michaelhush** [comment]
Changing reviewer to Andre

**Comment by ViktorPerunicic** [comment]
@andrerrcarvalho see the current updates - the two NB should follow the same style now

**Pull request merged**
