### PR TITLE
Dephasing_robust_controls_from_open_controls_plus_an_optimized…

### PR DESCRIPTION
**Pull request by ViktorPerunicic**
The notebook is currently as braif and to the point as possible... note, to keep the flow as neat, the plotting of FFs is done wia a helper method (which should be replaced by a qctrlvisualiser functionality in time). Let's agree on the structure etc. and I'll roll this over to the remaining NBs of thy type.

### CODE REVIEW

**Comment by michaelhush** [comment]
Good start. 

1. In terms of the code, I would prefer if we used the same "system" configuration to calculate all the filter functions? Constantly rebuilding it seems silly. Is this possible?

2. I don't need to see the plots of the individual filter functions. I would be happy if they were all calculated in a loop. Then all plotted in one cell.

3. After you plot the best filter function, can you make sure you highlight that the optimized one is the fastest. 

4. Could you add a primitive pulse for comparison.

**Comment by ViktorPerunicic** [comment]
1 & 2:   Ok will tray: I actually wrote in a way where that would be easy to put in a loop :) . About the system regeneraiton, it should be possible by directly edidint the control segments, but note, this is not what factories do. So I would still set up the system, using e.g. the primitive pulse, then put a loop and edit the control segments later (the this is that controls are in just dumped in a list, so I'll have to do it in a way that is neither confusing to users not too  heavy code-wise)

3. I have a note on that in the Compare section:  Note, I couldn't make optimised pulses more than 1.8 times faster for the same max Rabi rate so that they would be comparable (they cannot have enough time to do full cancellation otherwise).

4. primitive is the 1st one I do - I hope we are looking at the same NB?

**Comment by michaelhush** [comment]
Fantastic, next step.

1. Change styling of OpenControls to Open Controls (add the space).

2. Add precisions to the plot. (Basically add a dotted line above and below the plots.)

3. In the text delete any claims about controls being better than one another if they are within each others precisions. I suspect this is why the optimized solution is winning in this case.

**Comment by ViktorPerunicic** [comment]
@michaelhush see some changes - and the plot at the end, it's hard to make ti look really good - but this is the loses I coma to the one for black opal

**Comment by michaelhush** [comment]
One more round I think.

1. The content of the text is good. I'll hand it over to @andrerrcarvalho to do final proofing. In terms of style @andrerrcarvalho could you make the text concise wherever possible.

**Comment by michaelhush** [comment]
2. @ViktorPerunicic the plotting looks great. One minor improvement, can you make sure the limits of the plot come right to the edge of the filter functions. I think the odd spacing on BLACK OPAL is a bug in this case rather than a design choice.

3. I think we're ready to start on qctrl-visualizer. @ViktorPerunicic could you pick that up? Book a meeting with me if you want to go over the details of the API.

**Comment by andrerrcarvalho** [comment]
I fixed a few typos and it looks good. The only remaining issue is lack of consistency when referring to the package. Sometimes we use Q-CTRL and in others Qctrl. @michaelhush , is there a standard here?

**Comment by ViktorPerunicic** [comment]
I would say these are different, Q-CTRL is a company branding, and Qctrl is the package name, but sometimes it's not clear which is better to use depending on what you want to be putting emesis on

**Comment by michaelhush** [comment]
To repeat slack messages incase Rob finds this. Company name is always stylized Q-CTRL, if you ever refer to the package you can use Q-CTRL Python Package or `qctrl`

**Comment by michaelhush** [comment]
@ViktorPerunicic could you fix at least 2. from my comment above and also change the name of the file and title to:
Filter functions of pulses that are robust to dephasing
filter_functions_of_pulses_that_are_robust_to_dephasing

**Pull request merged**
